name: "docusaurus"
services:
  dev:
    build:
      context: .
      target: prod
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/docusaurus
    environment:
      - NODE_ENV=prod